# Site wide configuration

title:            Chris' Playground
locale:           en_US
url:              https://chrismacnaughton.com


# Jekyll configuration

permalink:   /blog/:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from

remote_theme: "mmistakes/minimal-mistakes@d4b4c890db45fbbf25b69fbc849ab49c2dc895f1"

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
  input: GFM

syntax_highlighter: rouge
# Octopress

# Default extensions
post_ext: md
page_ext: md

# Found in _templates/
post_layout: single
page_layout: single

# Format titles with titlecase?
titlecase: true

paginate: 15 # amount of posts to show
paginate_path: /page:num/

analytics:
  provider: "google" # false (default), "google", "google-universal", "custom"
  google:
    tracking_id: UA-35809231-1
    anonymize_ip: true # true, false (default)

minimal_mistakes_skin: air
repository: "ChrisMacNaughton/chrismacnaughton.github.com" # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
comments:
  provider: "staticman_v2"

staticman:
  branch: "master"
  allowedFields          : ['name', 'email', 'url', 'message']
  commitMessage          : "New comment."
  filename               : comment-{@timestamp}
  format                 : "yml"
  moderation             : true
  path                   : "_data/comments/{options.slug}"
  requiredFields         : ['name', 'email', 'message']
  transforms:
    email                : "md5"
  generatedFields:
    date:
      type               : "date"
      options:
        format           : "iso8601" # "iso8601" (default), "timestamp-seconds", "timestamp-milliseconds"
reCaptcha:
  enabled: true
  siteKey: "6Lfbi1QUAAAAANBEdQxrgJyiGDw9yuK0wUnzzwv6"
  secret: "cUucy6iq6ByyQ03Cy0f/h+zpWlvN9/zcKjT5l81RFEYDAdmvScQ8dRDy76KJnSKASkdAxP6oQip2JBqGpp53vS+BcfHxt+HBrGGiBLr/WtVBUsge8HLKOcr7M6Qr/ErWb2MhHbqHTWHjXnxwjN0AFjmN2t6plCf+CsK4pJYN43Q="
search: true
search_full_content: true
# Site owner
author:
  name: Chris MacNaughton
  avatar: assets/images/me.jpg
  bio: |
    Chris MacNaughton currently works on the Ecosystem Engineering team at
    Canonical Ltd, focusing on storage technologies for OpenStack deployments.
  email: chris@macnaughton.email
  twitter: chrismacn
  facebook: chris181m
  keybase: chrismacnaughton
  google:
    plus: ChrisMacNaughton1
    verify: 8IAO7pVpsIeL_ckvBKWdDNiNOruQOqRfjsHDZAhz0FM
    ad-client:
    ad-slot:
  bing-verify:
  github: chrismacnaughton
  stackoverflow: 1527069/iceyec
  linkedin: chrismacnaughton
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username

include: ["_pages"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/

tag_archive:
  type: liquid
  path: /tags/

compress_html:
  clippings: all
  ignore:
    envs: development  # disable compression in dev environment

breadcrumbs: true

timezone: Europe/Amsterdam