# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Chris' Playground
email: chris@macnaughton.email
description: > # this means to ignore newlines until "baseurl:"
  Chris MacNaughton currently works on the Ecosystem Engineering team at
  Canonical Ltd, focusing on storage technologies for OpenStack deployments.
permalink: /blog/:year/:month/:day/:title/
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://chrismacnaughton.com" # the base hostname & protocol for your site
twitter_username: chrismacn
github_username:  chris.macnaughton

# Build settings
markdown: kramdown
# safe: true

gems: ['jekyll-paginate']
paginate: 5
paginate_path: 'blog/:num/'